// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from helloworld.djinni

#pragma once

#include <memory>
#include <string>

namespace helloworld {

class HelloWorld {
public:
    virtual ~HelloWorld() {}

    /** return an instance of our C++ object with the methods we outline in this IDL file */
    static std::shared_ptr<HelloWorld> create();

    /** function taht returns a string */
    virtual std::string get_hello_world() = 0;
};

}  // namespace helloworld
