// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from helloworld.djinni

#import <Foundation/Foundation.h>
@class HWHelloWorld;


@interface HWHelloWorld : NSObject

/** return an instance of our C++ object with the methods we outline in this IDL file */
+ (nullable HWHelloWorld *)create;

/** function taht returns a string */
- (nonnull NSString *)getHelloWorld;

@end
